ignorePatterns:
  - "dist"
parser: "@typescript-eslint/parser"
extends:
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - prettier
  - plugin:prettier/recommended
  - plugin:react-hooks/recommended
settings:
  react:
    version: detect
parserOptions:
  ecmaVersion: 2018
  sourceType: "module"
rules:
  "@typescript-eslint/camelcase": off
